# Generated by Django 4.0.1 on 2022-01-24 16:12

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='img/lesson_default.png', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 300], upload_to='lesson_images'),
        ),
    ]
