# Generated by Django 4.0.1 on 2022-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=25),
        ),
    ]
