# Generated by Django 4.0.1 on 2022-01-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_ext_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
