# Generated by Django 4.0.1 on 2022-01-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
