# Generated by Django 4.0.1 on 2022-01-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
    ]
